[package]
name = "cryptography-algo"
version = "0.1.0"
authors = ["alexxuyang <alexxuyang@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"
prime_tools = "0.2.2"
primes = "0.2.4"
